# This file is used to run the backend with memcached as a cache. (Not in use).
services:
  memcached:
    image: memcached:latest
    container_name: memcached_container
    ports:
      - "${MEMCACHED_PORT}:${MEMCACHED_PORT}"
    restart: always
