services:
  memcached:
    image: memcached:latest
    container_name: memcached_container
    ports: 
      - "${MEMCACHED_PORT}:${MEMCACHED_PORT}"
    networks:
      - kaluste-network
    restart: always

  kaluste-backend:
    container_name: kaluste_backend_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - memcached
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MEMCACHED_HOST: ${MEMCACHED_HOST}
      MEMCACHED_PORT: ${MEMCACHED_PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - kaluste-network
    command: npm start

networks:
  kaluste-network:
    driver: bridge